In [43]:
import  pandas as pd

In [44]:
import numpy  as np

In [45]:
df=pd.read_csv("sales.csv")

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

In [47]:
df.head(10)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5,4.0,20.0,Credit Card,NaN,2023-03-31
6,TXN_4433211,UNKNOWN,3,3.0,9.0,ERROR,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4,4.0,16.0,Cash,UNKNOWN,2023-10-28
8,TXN_4717867,NaN,5,3.0,15.0,NaN,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,5,4.0,20.0,NaN,In-store,2023-12-31

In [48]:
df.isna().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [49]:
df=df.dropna()

In [50]:
df.isna().sum()

Transaction ID      0
Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
dtype: int64

In [51]:
df.duplicated().sum()

np.int64(0)

In [52]:
df=df.drop_duplicates()

In [53]:
df.head(10)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
6,TXN_4433211,UNKNOWN,3,3.0,9.0,ERROR,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4,4.0,16.0,Cash,UNKNOWN,2023-10-28
10,TXN_2548360,Salad,5,5.0,25.0,Cash,Takeaway,2023-11-07
11,TXN_3051279,Sandwich,2,4.0,8.0,Credit Card,Takeaway,ERROR
12,TXN_7619095,Sandwich,2,4.0,8.0,Cash,In-store,2023-05-03

In [54]:
df['Transaction ID'].unique()

array(['TXN_1961373', 'TXN_4977031', 'TXN_4271903', ..., 'TXN_3897619',
       'TXN_2739140', 'TXN_6170729'], dtype=object)

In [55]:
df['Item'].unique()

array(['Coffee', 'Cake', 'Cookie', 'Salad', 'UNKNOWN', 'Sandwich',
       'Juice', 'Smoothie', 'ERROR', 'Tea'], dtype=object)

In [58]:
df=df[~df.isin(["UNKNOWN","ERROR"]).any(axis=1)]

In [60]:
df['Quantity']=df['Quantity'].astype(int)

In [61]:
df[df.isin(["UNKNOWN","ERROR"])].sum()

Transaction ID        0
Item                  0
Quantity            0.0
Price Per Unit        0
Total Spent           0
Payment Method        0
Location              0
Transaction Date      0
dtype: object

In [62]:
df['Price Per Unit']=df['Price Per Unit'].astype(float)

In [63]:
df['Total Spent']=df['Total Spent'].astype(float)

In [67]:
df['Transaction Date']=pd.to_datetime(df['Transaction Date'])

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3089 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    3089 non-null   object
 1   Item              3089 non-null   object
 2   Quantity          3089 non-null   int64
 3   Price Per Unit    3089 non-null   float64
 4   Total Spent       3089 non-null   float64
 5   Payment Method    3089 non-null   object
 6   Location          3089 non-null   object
 7   Transaction Date  3089 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 217.2+ KB

In [69]:
df.to_csv('cleaned_sales.csv', index=False)

This will save your `df` DataFrame to a file named `cleaned_sales.csv` in your local machine. The `index=False` argument prevents pandas from writing the DataFrame index as a column in the CSV file.